---
- name: install redsocks
  apt:
    name: redsocks
    state: present

- name: copy redsocks config
  template:
    src: redsocks.conf.j2
    dest: /etc/redsocks.conf

- name: restart redsocks service
  systemd:
    name: redsocks
    state: restarted
